filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["log", "message"]
        target: ""
        overwrite_keys: true
        add_error_key: true
        process_array: false
    - drop_event:
        when:
          not:
            or:
              - contains:
                  message: "port 2375"
              - contains:
                  message: "TCP connection"
              - contains:
                  message: "network connection"
              - contains:
                  message: "scan"
              - contains:
                  message: "GET /"
              - contains:
                  message: "POST /"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-network-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
